### PR TITLE
add Exit feature -- does a Halt+Destroy

### PR DESCRIPTION
**Pull request by jhakala**
This should enable us to do things on the "Halt" transition reliably at the end of runs, e.g. TCDS lease expiration.

### CODE REVIEW

**Comment by jhakala** [comment]
This was tested and seems to work fine, I suggest we merge it now.

**Comment by jhakala** [comment]
Done in 3cd689e.

**Comment by kakwok** [comment]
I forgot to put this in the last request, can we have the normal destroy button popped up in the GUI automatically when we're in ERROR?

**Comment by jhakala** [comment]
restoring the Destroy button in an Error state: done in  b9277c2

**Pull request merged**
