### PR TITLE
New control panel

### PR DESCRIPTION
**Pull request by jhakala**
New GUI. Looks better, takes up less space, fits better on smaller windows, and the jsp code is cleaned up significantly.

Please test and give feedback.

PS: It would be great to get #313 merged first so that I can get rid of this "Modify?" button that we have now.

image

### CODE REVIEW

**Comment by jhakala** [comment]
I realized that two small changes are required:
   * The Quick Info shows the FM name instead of the configuration name; this is a bug introduced by me reordering them, and the way the JS identifies the quick info. Can be easily fixed by getting the configuration name by ID rather than class.
   * If a configuration name (or FM name) is very long, it will cause weird formatting of the page. If a configuration name is too long, it should be put into a box with hidden overflow and right-aligned text (so that you see the _end_ of the configuration name, which is usually the important part). Then the box should either be stretchable or pop into the foreground in case you need to read the full long name. In any case, configuration and FM names usually aren't (and shouldn't) be very long so it's not a big issue.

(this is mostly a to-do list for my own memory)

**Comment by kakwok** [comment]
- View Run Parameters and View Global Parameters seems to be broken for me. The table has no content inside.
- I like the `SetEnableParameters` and `Initialise` button are in same place now! 
- Host did not get the alias.
- The `Group, FullPath...StatusDisplay` buttons changes position when we go from initial->Halted. Maybe fix it to the position when we have more command buttons
image
How about just like below, but make it two rows of 4 buttons fixed in the positions like that (StatusTable,StatusDisplay,Destroy,Detach in one row fixed and the top four buttons will change depending on status) 
image

- Font sizes are not consistent
 Buttons should have a larger fonts? Or Events Taken/GroupName should have same fonts
- `Running Configurations`/`Configuration Choser` are an frequently used buttons, but got pushed to boundaries with small fonts.

**Comment by jhakala** [comment]
Here is a checklist of the different things we discussed in our chat about the new GUI. Those marked with an `X` are done in one way or another, and those marked with a `-` are still TODO's.

```
Notes on new HCALFM GUI:
 X move running configurations to above state
 - move mask checkboxes next to number of events or other display of mask summary
 X move framework links below, 30 width, vertical centering of text
 X make full path more prominent
 X move full path, run number, run key above state, change name "full path"600
 X also move spectate button there
 X we can remove group name and full path
 X keep destroy and detach under progress bar
 X FM command buttons in a row
 X below row keep status display and status table4
 X put destroy in a special place
 X screenshot, but with status table on same line as destoy, destroy all to the right, also add the refresh button
 - progress bar color
 - make progress bar solid for not running/configuring
 - consider animating and getting initialization progress
```

Here is what the GUI looks like as of now:
image

I think the remaining items are not super crucial; could we consider doing the rest of those later as side projects? If so then please test and let me know if there are any further comments.

**Comment by jhakala** [comment]
note to self: fix quick info config name

**Comment by kakwok** [comment]
Comments from HCALSW meeting Oct30
```
- Make runkey more easily noticeable (as is, the key is pushed to far right)  
- Make the `spectate` v.s. `control` more drastic than greying buttons (Big RED words popping up somewhere?
```

**Comment by kakwok** [comment]
Testing error message at 904
image

**Comment by kakwok** [comment]
Got general good feedback from users! Green-light to deploy!

**Pull request merged**
