### PR TITLE
Add get prop utility func

### PR DESCRIPTION
**Pull request by sethcooper**
For extracting config properties by name from the Duck template db.

### CODE REVIEW

**Comment by jhakala** [comment]
Probably want to get Function Manager properties rather than Configuration properties.

**Comment by sethcooper** [comment]
I was wondering about that. Do you have the correct code handy?

**Comment by jhakala** [comment]
We had something in the old days for getting the properties assigned to the TCDS executives (and I think this would work generically for any 'resource' including FMs.)
`                List<QualifiedResource> xdaqExecutiveList = qg.seekQualifiedResourcesOfType(new XdaqExecutive());
                for (QualifiedResource qr : xdaqExecutiveList) {
                    List<ConfigProperty> propertyList = qr.getResource().getProperties();
                    for(ConfigProperty property : propertyList ) {
                        if(property.getName().equals("static")
                           && property.getType().equals("bool")
                           && property.getValue().equals("true") ) qr.setInitialized(true);
                    }
                }`

**Comment by kakwok** [comment]
These two lines do the same thing. Seth's code is already getting FM's properties.
`List<ConfigProperty> propertyList = qr.getResource().getProperties();`
`List<ConfigProperty> propertiesList = getGroup().getThisResource().getProperties();`

**Pull request merged**
