### PR TITLE
Automate build script for making release tags

### PR DESCRIPTION
**Pull request by kakwok**
Release convention: `yy.xx.zz`   where `yy` = year, `xx`= major version, `zz`=minor version
`./buildHCALFM.sh release major` will increase `xx` by 1
`./buildHCALFM.sh release`  will increase `zz` by 1
- Added link to the commit hash corresponding to the version number in GUI 
- The script will automaticlly sync the central remote repository's list of tags and calculate the correct version number. 
- Allow private fork to have tags other than releases on remote, but having other tags in local may confuse the version number update.

The original `release` feature which builds a jar with a commit hash has been moved to 
`./buildHCALFM.sh hash`

### CODE REVIEW

**Comment by kakwok** [comment]
@jhakala How about `./buildHCALFM.sh release yy.xx.zz` to build the release version requested? Then for minor release update, we should require the third argument like `./buildHCALFM.sh release minor`

**Comment by jhakala** [comment]
Sounds good.

**Comment by kakwok** [comment]
Implemented. When building an existing tag, the build script will
- check if input tag matches any of the existing tags
- move to a new branch for that tag ( to avoid getting into detached state)
- build the jar, and delete the temporary build branch.
- return to the previous branch  
The diff w.r.t. previous state is here: 
https://github.com/HCALRunControl/levelOneHCALFM/compare/b75006263ffc9a8b0d3d583bee5891deeaa82199...testRelease

**Comment by jhakala** [comment]
Great, I tested it and it works nicely. I even tried to tag a broken FM and it prevented me.

One question though: I know you were thinking about changing how we use master and integration and etc, so what do you think about requiring the releases to be built off of one of those "special" branches?

**Comment by kakwok** [comment]
Great! 
I am thinking to follow closely the hcos model: 
- master HEAD will be production used by global config, 
- integration HEAD will be local FM + approved new features/commits

When we deploy to global, we do 
- move the symlink
- merge `integration` to `master`
- pick the tag to be release.

Keeping master head to be production makes hot-patches easier to make.

**Pull request merged**
