### PR TITLE
More GUI improvements

### PR DESCRIPTION
**Pull request by jhakala**
GUI updates implementing a few different things.

- Make parameters that overflow their boundaries viewable:
image
image

- Button for one-click copy of Quick Info. (#330)
image

- Show masked FMs (#272), and remove quick info display (as it is fully redundant)
image

- Swap positions of "Set" and "Autoconfigure" buttons. (#335)
image

Please test and give feedback.

### CODE REVIEW

**Comment by kakwok** [comment]
Thanks for implementing these issues!
2 questions:
 - Would EMPTY_FM be displayed alongside with MASKED FMs as well? I think that's more hidden than MASKED FMs because the checkboxes were presented to users.
 - Do we want to keep the quick info line together with the button? Just a thought that the line will be more noticeable than the button.

**Comment by jhakala** [comment]
> Would EMPTY_FM be displayed alongside with MASKED FMs as well? I think that's more hidden than MASKED FMs because the checkboxes were presented to users.
Not currently. The focus of this PR is mostly on usability in local. That and some other issues could be fixed in a dedicated update for improving the way things look while we are in global (I get the impression that looking at the level1 GUI during global runs is not that common).

> Do we want to keep the quick info line together with the button? Just a thought that the line will be more noticeable than the button.
@elaird specifically requested we remove the Quick Info box. It could be restored if you prefer.

**Comment by jhakala** [comment]
Think we could get this tested and hopefully merged soon? These changes are mostly harmless so it would be good if we could roll things out before splashes/beams.

**Comment by kakwok** [comment]
OK fine.

**Pull request merged**
