### PR TITLE
Close Logsession properly

### PR DESCRIPTION
**Pull request by kakwok**
Fix logsession for real....
 -  LV1 should try to close any open session ID not requested by LV0
 - Note: 
`RunType` was set by EventHandler _after_ `initXDAQ()`, which could possibly fail.
`containerFMchildern` is also set inside _after_ `qg.init()`, so should not be used.
- `INITIALIZED_WITH_SID` is parameter for LV0, which is set once we obtained from LV0.
- `INITIALIZED_WITH_SID` was declared as StringT in HCALParameters, but was used as IntegerT when SID is given from LV0.

### CODE REVIEW

**Comment by kakwok** [comment]
The messages are mostly at debug level except the print out of current session info, which I have just removed in 5693c76. So, now there is only 1 info message telling us going to close the session or if not, then why. I think that's reasonable.
If the connector is null or LogSessionException, the SID will default to 0, can we live with that? I think we can still get run number? Also we will use SID for TCDS hardware leasing session soon too, although naively I also think having SID=0 would prevent us from taking runs.
Teststand compatibility maybe an issue too, like what happened to RunInfo at H2.

**Comment by sethcooper** [comment]
I think we can live with SID==0, but it's usually signaling that something went wrong at the level of the DB, and eventually we should address it.  So I think we need something stronger than a warning in the log (or else no one will notice).  Maybe this is a case for RunningDegraded? That might be OK if it is clear that in this case the reason is SID==0.  (SID==0 by itself won't mess up TCDS leasing.)  There are probably a few use cases for FM-triggered RunningDegraded states.

For H2, I think eventually a MySQL LogSession DB was implemented, right? At least I'm pretty sure they have "official" run numbers now.  If that is the case then we shouldn't need to worry about teststands, since we should be able to make MySQL LogSession DBs for each of them in the worst case.  (Also if the worst consequence is RunningDegraded, then that's probably fine as well. And maybe the RunningDegraded could be disable-able even for FM-triggered RunningDegraded conditions).

**Comment by jhakala** [comment]
I think SID==0 isn't so bad we should break taking a run, but maybe we should make sure we're skipping publishing runinfo when that's the case (Hannes complained about this earlier). It's not clear how it would be possible to get a run number without an SID (unless there's a bug like we had before) so runinfo that's published without a meaningful run number is probably useless and only clogs the DB.

**Comment by sethcooper** [comment]
We do get proper run numbers even with SID==0. This was happening (again) Friday in 904. So I think we just need to somehow alert the user (in a better way than just a log message) that there may be a DB issue.

**Pull request merged**
