### PR TITLE
Handle TCDS by FM

### PR DESCRIPTION
**Pull request by kakwok**
For #204 
-TCDS controllers(LPM, PI, iCI) are converted to service apps on-the-fly
-Update the TCDS controller containers to `XdaqServiceApplicationContainer`   
-Life-cycle of TCDS service apps are not controlled by us, so always skip init for TCDS executives
-FM handles the service apps only in 2 ways:
1) send halt during `haltAction` and `resetAction`  
2) configure them with parameters during `configureAction` 
-Framework will bring the service apps to `Halted` after init, we don't have to do that anymore.
-We obtain the TCDS hardware lease by RCMS SID, which needs to be set in the FM's QualifiedGroup to initialize the service apps.

Remark:
1. Conversion of TCDS apps modifies the FM's original QualifiedGroup. We should get the FM's latest QG before trying to get anything from it.
2. TCDS apps conversion needs to be done after `initXDAQ()`. After the conversion, we set the SID of the QG.

Tests:
Done with `uTCAcrate52_VME_TCDS_LPM_FMtest`with both global and local runkey. 
Normal cycle (Init->Configured->Start->Running->Stop->Halt+Destroy) works. 
Tested special transitions:
-Halt from Configured (Before and after run)
-Reset from Configured
-Halt from Halted
-Reset from Halted

### CODE REVIEW

**Comment by sethcooper** [comment]
Making it a parameter means that in the new scheme, we can automatically specify a value for it in the master snippet, right?

**Comment by kakwok** [comment]
Yes with the new commit.  b05a147 can serve as an example for passing any parameter.

**Comment by sethcooper** [comment]
One important to-do item before merging I neglected before: TCDS needs to be configured before the supervisor. So we need to schedule that in the level2 configure task sequence. This means that the monster sendRunType... function that _also_ configures the supervisor has to be broken up a bit. Hopefully this is not too difficult.

**Comment by jhakala** [comment]
We should PR this to fixMaster--unfortunate githell was caused by the new github merge webtool

**Comment by kakwok** [comment]
I took out the part of sending configure command to supervisor in `sendRunTypeConfiguration` Now the function merely sets up the infospace(s) of TTCci, LTC and supervisors.
The configure command to supervisor is scheduled after TCDS configurations task.

**Comment by kakwok** [comment]
We should start the review again when this is ready.

**Pull request closed without merging**
